### PR TITLE
Fix issue with saving bytestring in database

### PR DESCRIPTION
**Pull request by joostsijm**
Prevent "incorrect salt" error when trying to decrypt the password at authorization.

### CODE REVIEW

**Comment by dternyak** [comment]
Thanks!

**Comment by Hudsonzp** [comment]
Why the switch flask_bcrypt to flask.ext.bcrypt?  I believe latter is deprecated?  flask_bcrypt works just fine.

**Comment by joostsijm** [comment]
@Hudsonzp I wasn't aware of the fact, my bad.

**Comment by Hudsonzp** [comment]
No worries!  Just wanted to point that out so it's most up to date =D.

**Pull request merged**
