### PR TITLE
Refreshment

### PR DESCRIPTION
**Pull request by viatsko**
To work with newest and coolest versions of libraries and python

### CODE REVIEW

**Comment by dternyak** [comment]
Most of these changes look really good.

Before I merge, I'm going to make a fork of your fork (forkception) to remove and gitignore `htmlcov`. I should probably have gitignored that from the start. We can then merge my fork into your fork, before finally merging to this repo.

If you want, you could beat me to it since it'll be one less step. I don't want to be a stickler for open-source stuff if you're busy though.

Thanks for doing this! I think it'll give the boilerplate a much needed facelift.

**Comment by viatsko** [comment]
Repo before my changes is 17.5 mb already, probably also because of webpack's dist directory, you might consider doing fresh bolerplate, e. g. 2.0? :)

**Comment by dternyak** [comment]
A 2.0 is not a bad idea at all. There's been a major update to Flask and I'm sure Javascript land has changed quite a bit.

I did open a PR with some of the directories removed against your fork. Once thats merged, I'll merge this in :)

Thanks again!

**Comment by dternyak** [comment]
Actually, I just noticed that I already had htmlcov in my app. In that case, I'm just going to go ahead and merge your changes.

**Pull request merged**
